SonarSource/sonar-update-center-properties

softvis3d.properties

SoftVis3D-Plugin is now adapted to the new directory layout concept of SonarQube 7.6. Compatibility versions adapted accordingly.

Add softvis3d plugin release 1.1.0

---

findbugs.properties

This is the latest version that works with SpotBugs 3.1.12.
* [Changelog](https://github.com/spotbugs/sonar-findbugs/releases/tag/3.11.0)
* [Download](https://github.com/spotbugs/sonar-findbugs/releases/download/3.11.0/sonar-findbugs-plugin-3.11.0.jar)
* [SonarCloud](https://sonarcloud.io/dashboard?branch=3.11.0&id=com.github.spotbugs%3Asonar-findbugs-plugin)

release sonar-findbugs 3.11.0 for latest SQ

---

authaad.properties

As noted in these places:
- https://community.sonarsource.com/t/rff-azure-active-directory-aad-authentication-plug-in-for-sonarqube-1-1/3117
- https://github.com/hkamel/sonar-auth-aad/issues/40
- https://github.com/hkamel/sonar-auth-aad/issues/45
_v1.0_ of sonar-auth-aad is only compatible up to SonarQube _v7.0_. Due to the unique index (uniq_external_id) being introduced on dbo.users, trying to upgrade from _v6.7_ to _v7.1_ or greater will cause a migration failure.
While a draft release (https://github.com/hkamel/sonar-auth-aad/releases/tag/1.1-RC2) is available to restore compatability, it has not seen an official release.
We should update the compatibility of _v1.0_

Update compatability for Azure AD Plugin

---

findbugs.properties

This is the latest version that works with SpotBugs 3.1.12. Unlike 3.11.0, this version supports SonarQube LTS but doesn't work with the latest one.
* [Changelog](https://github.com/spotbugs/sonar-findbugs/releases/tag/3.9.4)
* [Download](https://github.com/spotbugs/sonar-findbugs/releases/download/3.9.4/sonar-findbugs-plugin-3.9.4.jar)
* [SonarCloud](https://sonarcloud.io/dashboard?branch=3.9.4&id=com.github.spotbugs%3Asonar-findbugs-plugin)

release sonar-findbugs 3.9.4 for SonarQube LTS

---

authaad.properties

Update properties file to reference the 1.1.0 version of Azure AD Auth for SonarQube

Release sonar-auth-aad 1.1.0

---

cpp.properties

As of SonarCFamily _v6.0_, we no longer support running analysis on a 32-bit machine. There is no Product News for this release where this was described, nor is it clear in the Release Notes.
A few customers have pinged us through Support and, while not upset that 32-bit support was dropped, are upset it was not clear to them before upgrading. I think this little note in the Marketplace could provide us some cover, and warn users in advance of upgrading.

Mention drop of 32-bit support in SonarCFamily v6.0

---

findbugs.properties

This is the latest version that works with SpotBugs 3.1.12.
* [Changelog](https://github.com/spotbugs/sonar-findbugs/releases/tag/3.11.1)
* [Download](https://github.com/spotbugs/sonar-findbugs/releases/download/3.11.1/sonar-findbugs-plugin-3.11.1.jar)
* [SonarCloud](https://sonarcloud.io/dashboard?branch=3.11.1&id=com.github.spotbugs%3Asonar-findbugs-plugin)

release sonar-findbugs 3.11.1 for latest SQ

---

authoidc.properties
guavamigration.properties
xanitizer.properties

See https://jira.sonarsource.com/browse/UPC-101
We now enforce correct ranges. Once we deploy UPC 1.23, this will fail deployment.

UPC-101 Correct version ranges

---

update-center-source.properties

SonarQube 6.7 through 7.8 are all considered EOL now that six months have passed since the new LTS was released.
Services Team discussed this and we are fully comfortable with this since no plugin updates have been released for 6.7 - 7.8 since the new LTS was released in July.

Move 6.7 - 7.8 to private versions

---

dependencycheck.properties

We've released sonar-dependency-check-plugin version 2.0.3, please add it to the marketplace.

Update sonar-dependency-check-plugin to 2.0.3

---

dependencycheck.properties

We've released sonar-dependency-check-plugin version 2.0.4, please add it to the marketplace.

Update sonar-dependency-check-plugin to 2.0.4

---

icode.properties

Add new version 2.0.2 of I-Code CNES plugin an change category from **External Analyzers** to **Languages**.

Add icode plugin 2.0.2

---

aemrules.properties

It appears https://github.com/SonarSource/sonar-update-center-properties/pull/112 came through with an erroneous link to the 1.1 binary
When viewed in the Marketplace, the plugin comes up as v1.0 and links to v1.1 docs. I belive this link to be the reason for that.
This PR aims to amend that. Please confirm if there's anywhere else the wrong metadata could be coming from.

Release: AEMRules v1.1 fix Jar link in metadata

---

cnesreport.properties
icode.properties

Organization `lequal` has been renamed `cnescatlab` please accept these change to get the updated links.
Sincerely,
Benoît

Change lequal to cnescatlab

---

dependencycheck.properties

We've released sonar-dependency-check-plugin version 2.0.6, please add it to the marketplace.

Update dependency-check-sonar-plugin to 2.0.6

---

findbugs.properties

We've released [sonar-findbugs version 4.0.2](https://github.com/spotbugs/sonar-findbugs/releases/tag/4.0.2), please add it to the marketplace.
Here is [my post at the forum for this change](https://community.sonarsource.com/t/new-release-sonar-findbugs-4-0-2/35166).

Release sonar-findbugs 4.0.2

---

dependencycheck.properties

We've released sonar-dependency-check-plugin version 2.0.7 please add it to the marketplace.

Update dependency-check-sonar-plugin to 2.0.7

---

cnesreport.properties

* Enable use of SonarQube context URL
* Fix date command line argument
* Fix version command line argument
And more... (https://github.com/cnescatlab/sonar-cnes-report/releases/tag/3.3.1)
Please note that the previous 3.3.0 request did not receive any answer, so this PR contains version 3.3.0 data too.

Update CNES Report plugin properties

---

apigee.properties

Declare release 3.0.0 for SQ 8.8+
Keep 2.1.1 for older SQ version
End of life of 2.0.0

sonar-apigee 3.0.0

---

hadolint.properties

* Update shell rules with Shellcheck plugin 2.4.0
* Update Dockerfile rules with Hadolint 2.6.1
* Add a default value for Dockerfiles list
* Add ability to list Hadolint reports using wildcards
* Fix an error whn using absolute paths for Hadolint reports
And more details here : https://github.com/cnescatlab/sonar-hadolint-plugin/releases/tag/1.1.0

Update Hadolint plugin with version 1.1.0

---

detekt.properties

We released `sonar-detekt` version `2.4.0`, see: https://github.com/detekt/sonar-kotlin/releases/tag/2.4.0
Sadly I don't have a SonarQube instance where I can try this, so I'm just copying the values from the previous version.

Update sonar-detekt to 2.4.0

---

detekt.properties

We released sonar-detekt version 2.5.0, see: https://github.com/detekt/sonar-kotlin/releases/tag/2.5.0
which now bundles Detekt 1.19.0.

Update sonar-detekt to 2.5.0

---

dependencycheck.properties

We've released sonar-dependency-check-plugin version 3.0.1, please add it to the marketplace.

Update sonar-dependency-check-plugin to 3.0.1

---

cnesreport.properties

* Some refactoring to ease future features
* Add tests metrics summary in report (total tests, success rate, failures, ...)
* Allow the plugin to run on non-compatible SonarQube releases (but show a warning)
* Some bugfixes
And more details here : https://github.com/cnescatlab/sonar-cnes-report/releases/tag/4.1.0
*Compatibility only includes 8.9.x LTS because we rely a lot on SQ APIs. 9.x versions may change them, and we don't have enough time to maintain the plugin for every intermediate SQ release before the next LTS.*

Add Sonar CNES Report version 4.1.0

---

aemrules.properties

Compatibility update to SonarQube 8.9 LTS. There have been breaking API changes in the Sonar Java plugin that AEM Rules use as a depenency. This release removes reliance on no longer available methods, preventing runtime failures.
Release 1.4 has been discarded, skipped and shouldn't be available for
download.

AEM Rules for SonarQube release 1.5

---

aemrules.properties

Reverts SonarSource/sonar-update-center-properties#284
UC error:
> The plugin 'java' is in version 6.5.1 whereas the plugin 'aemrules' requires a least a version 6.15.

Revert "AEM Rules for SonarQube release 1.5"

---

.github/CODEOWNERS

According to https://xtranet-sonarsource.atlassian.net/wiki/spaces/RE/pages/2169339970/GitHub+Authentication+Authorization#CODEOWNERS, only one team can be the "owner".

Remove individuals from ownership

---

pmd.properties

We released a new version of the sonar-pmd-plugin to support Java 18 and Sonar 8.9/9. Please make it available in the marketplace. Thanks!

new sonar-pmd-plugin: 3.4.0

---

crowd.properties

https://community.sonarsource.com/t/sonarqube-does-not-get-user-info-from-crowd-after-update-to-9-4/63860

shorten compatibility range per community

---

cnesreport.properties

* Fix a bug on project name with special chars on Windows
* Add missing Security Hotpsots categories
* Add missing data on external issues
* Fix a warning seen in logs
And more details here : https://github.com/cnescatlab/sonar-cnes-report/releases/tag/4.1.2
*Compatibility only includes 8.9.x LTS because we rely a lot on SQ APIs. 9.x versions may change them, and we don't have enough time to maintain the plugin for every intermediate SQ release before the next LTS.*
PS : We also noticed that CNES Report plugin won't be allowed in the SonarQube Marketplace starting with its 9.5 release, because the Enterprise edition now has similar features. We will only publish updates for 8.9 then, so that may be one of our last PR... :cry:

Add CNES Report version 4.1.2

---

ibmixaemrules.properties

Version 1.2 release of the ibmix-aem-sonar-rules plugin

ibmix-aem-sonar-rules 1.2

---

l10nzh.properties

Hi,
sonar-l10n-zh-plugin-9.7 has been released.
The main changes is support SonarQube 9.7.
The Download link and release notes: https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-9.6/sonar-l10n-zh-plugin-9.7.jar
Thank you
Regards

sonar-l10n-zh-plugin-9.7

---

apigee.properties

Declare release 3.0.2 for SQ 9.7+  (fix for https://github.com/CreditMutuelArkea/sonar-apigee-plugin/issues/15 )
Keep 3.0.1 for older SQ versions

Declaration of release 3.0.2 (support for SQ 9.7+)

---

l10nzh.properties

Hi,
sonar-l10n-zh-plugin-9.8 has been released.
The main changes is support SonarQube 9.8.
The Download link and release notes: https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-9.8/sonar-l10n-zh-plugin-9.8.jar
Thank you
Regards

sonar-l10n-zh-plugin-9.8

---

l10nfr.properties

Hi,
sonar-l10n-fr-plugin-9.8.0 has been released.
NB: Repository has changed of ownership (from https://github.com/ZoeThivet/sonar-l10n-fr to https://github.com/jycr/sonar-l10n-fr)
The main changes is support SonarQube 9.8.
The Download link and release notes: https://github.com/jycr/sonar-l10n-fr/releases/tag/9.8.0
The SonarCloud: https://sonarcloud.io/project/overview?id=jycr_sonar-l10n-fr
Thank you
Regards

sonar-l10n-fr-plugin-9.8.0

---

scannergradle.properties

The SQ documentation website pulls content from this file and displays it at the [top of the SonarScanner for Gradle page](https://docs.sonarqube.org/latest/analyzing-source-code/scanners/sonarscanner-for-gradle/). It has been reported that the build numbers must be included to prevent build ID errors.

update SonarScanner for Gradle version numbers to include build number

---

l10nfr.properties

Hi,
sonar-l10n-fr-plugin-9.8.1 has been released.
Changes:
- Fix misleading translations
- Implement epicene writing
The Download link and release notes: https://github.com/jycr/sonar-l10n-fr/releases/tag/9.8.1
The SonarCloud: https://sonarcloud.io/project/overview?id=jycr_sonar-l10n-fr
Thank you
Regards

sonar-l10n-fr-plugin-9.8.1

---

l10nzh.properties

Hi,
sonar-l10n-zh-plugin-9.9 has been released.
The main changes is support SonarQube 9.9.
The Download link and release notes: https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-9.9/sonar-l10n-zh-plugin-9.9.jar
Thank you
Regards

sonar-l10n-zh-9.9

---

dependencycheck.properties

We've released sonar-dependency-check-plugin version 3.1.0, please add it to the marketplace.
A short description of the change can be found in the [SonarCommunity forum](https://community.sonarsource.com/t/new-release-sonar-dependency-check-plugin-3-1-0/84683).

Update sonar-dependency-check-plugin to 3.1.0

---

l10nzh.properties

Hi,
sonar-l10n-zh-plugin-10.0 has been released.
The main changes is support SonarQube 10.0.
The Download link and release notes: https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-10.0/sonar-l10n-zh-plugin-10.0.jar
Thank you
Regards

sonar-l10n-zh-plugin-10.0

---

dependencycheck.properties

We've released sonar-dependency-check-plugin version 4.0.0, please add it to the marketplace.
SonarCloud-Dashboard: https://sonarcloud.io/dashboard?id=dependency-check_dependency-check-sonar-plugin

Update sonar-dependency-check-plugin to 4.0.0

---

l10nfr.properties

Hi,
sonar-l10n-fr-plugin-9.9.1 has been released.
Changes:
* Fixes misleading translations
* Improves "CI" translations
* Uses right apostrophe quotation mark
The Download link and release notes: https://github.com/jycr/sonar-l10n-fr/releases/tag/9.9.1
The SonarCloud: https://sonarcloud.io/project/overview?id=jycr_sonar-l10n-fr
Thank you
Regards

sonar-l10n-fr-plugin-9.9.1

---

l10nfr.properties

Hi,
sonar-l10n-fr-plugin-10.0.0 has been released.
Changes:
* Support SonarQube 10.0
The Download link and release notes: https://github.com/jycr/sonar-l10n-fr/releases/tag/10.0.0
The SonarCloud: https://sonarcloud.io/project/overview?id=jycr_sonar-l10n-fr
Thank you
Regards

sonar-l10n-fr-plugin-10.0.0

---

ecocodejava.properties
ecocodephp.properties
ecocodepython.properties

Hi,
ecoCode plugins 1.3.0 (for languages: Java PHP, Python) have been released.
Changes:
* Support SonarQube 10.0
* https://github.com/green-code-initiative/ecoCode/issues/191
* Adds rules for Python language:
* `EC10` : https://github.com/green-code-initiative/ecoCode/pull/190
* `EC66` : https://github.com/green-code-initiative/ecoCode/issues/108
* `EC203` : https://github.com/green-code-initiative/ecoCode/pull/192
* `EC404` : https://github.com/green-code-initiative/ecoCode/issues/127
* Adds rules for PHP language:
* `EC3` : https://github.com/green-code-initiative/ecoCode/issues/109
The corresponding SonarCloud project: https://sonarcloud.io/summary/new_code?id=green-code-initiative_ecoCode&pullRequest=206
Thank you
Regards

Upgrade ecoCode plugins to 1.3.0 for languages: Java, PHP, Python

---

l10nzh.properties

Hi,
sonar-l10n-zh-plugin-10.1 has been released.
The main changes is support SonarQube 10.1.
The Download link and release notes: https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-10.1/sonar-l10n-zh-plugin-10.1.jar
Thank you
Regards

support sonarqube-10.1

---

l10nzh.properties

Hi,
sonar-l10n-zh-plugin-10.2 has been released.
The main changes is support SonarQube 10.2.
The Download link and release notes: https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-10.2/sonar-l10n-zh-plugin-10.2.jar
Thank you
Regards

sonar-l10n-zh-plugin-10.2 support SonarQube-10.2

---

l10nzh.properties

Hi,
sonar-l10n-zh-plugin-10.3 has been released.
The main changes is support SonarQube 10.3.
The Download link and release notes: https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-10.3/sonar-l10n-zh-plugin-10.3.jar
Thank you
Regards

sonar-l10n-zh-plugin-10.3

---

dependencycheck.properties

We've released sonar-dependency-check-plugin version 4.0.1, please add it to the marketplace.
SonarCloud-Dashboard: https://sonarcloud.io/dashboard?id=dependency-check_dependency-check-sonar-plugin

Update sonar-dependency-check-plugin to 4.0.1

---

l10nzh.properties

Hi,
sonar-l10n-zh-plugin-10.4 has been released.
The main changes is support SonarQube 10.4.
The Download link and release notes: https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-10.4/sonar-l10n-zh-plugin-10.4.jar
Thank you
Regards

sonar-l10n-zh-10.4

---

openedge.properties

Link to 2.24.2 was [broken](https://github.com/SonarSource/sonar-update-center-properties/pull/486#issuecomment-1916563000), so you had to remove it. This PR brings the latest version. Sorry for the annoyance !

OpenEdge plugin 2.24.3

---

ibmixaemrules.properties

Version 1.4 release of the ibmix-aem-sonar-rules plugin
SonarCloud dashboard - https://sonarcloud.io/summary/new_code?id=ibmix-aem-sonar-rules

Release ibmix-aem-sonar-rules plugin v1.4

---

l10nzh.properties

Hi,
sonar-l10n-zh-plugin-10.5 has been released.
The main changes is support SonarQube 10.5.
The Download link and release notes: https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-10.5/sonar-l10n-zh-plugin-10.5.jar
Thank you
Regards

Update sonar-l10n-zh-10.5 for Sonarqube-10.5.

---

po-generate-update-center-prod/upload-sc.sh
po-generate-update-center-prod/upload.sh

Due to infrastructure changes to remove the public access to S3 buckets, the original JMESPATH query is failing on the array index.
This new query is more generic.

fix(BUILD-5327): find cloudfront distribution ID

---

scannerazure.properties
scannerazuresc.properties

The repository was recently renamed to sonar-scanner-azdo, and the Jira project SONARAZDO, this PR reflects this change to this repository
See [ticket](https://sonarsource.atlassian.net/browse/BUILD-5236) for context

BUILD-5236 Rename VSTS to AzDO

---

update-center-source-sc.properties

Change from ltsVersion to ltaVersion because it looks to be mandatory to deliver the Update Center for SC

ltsVersion to ltaVersion

---

l10nzh.properties

Hi,
sonar-l10n-zh-plugin-10.6 has been released.
The main changes is support SonarQube 10.6.
The Download link and release notes: https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-10.6/sonar-l10n-zh-plugin-10.6.jar
Thank you
Regards

sonar-l10n-zh-plugin-10.6 support SonarQube-10.6

---

.cirrus/Dockerfile

BUILD-5727 Use JDK21 LTS instead of JDK19 EOL

---

l10nzh.properties

Hi,
sonar-l10n-zh-plugin-10.7 has been released.
The main changes is support SonarQube 10.7.
The Download link and release notes: https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-10.7/sonar-l10n-zh-plugin-10.7.jar
Thank you
Regards

sonar-l10n-zh-10.7

---

po-generate-update-center-prod/.envrc
po-generate-update-center-prod/README.md
po-generate-update-center-prod/aws_sso_profiles.conf

The vault credentials should not be used for manual deployment. Using the AWS role `RECDNElevatedStaging` instead

BUILD-6540: Use new AWS profile instead of vault credentials

---

communitydelphi.properties

SonarDelphi v1.12.0 has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.12.0)
Thanks!

Release SonarDelphi plugin v1.12.0

---

communitydelphi.properties

SonarDelphi v1.12.1 has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.12.1)
Thanks!

Release SonarDelphi plugin v1.12.1

---

l10nzh.properties

Hi,
sonar-l10n-zh-plugin-10.7 has been released.
The main changes is support SonarQube 24.12.
The Download link and release notes: https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-24.12/sonar-l10n-zh-plugin-24.12.jar
Thank you
Regards

sonar-l10n-zh-24.12

---

communitybsl.properties

Hello there. communitybsl 1.15.1 is out. 
SonarCloud project: https://sonarcloud.io/project/overview?id=1c-syntax_sonar-bsl-plugin-community

communitybsl: update 1.15.1

---

l10nzh.properties

Hi,
sonar-l10n-zh-plugin-25.1 has been released.
The main changes is support SonarQube 25.1.
The Download link and release notes: https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-25.1/sonar-l10n-zh-plugin-25.1.jar
Thank you
Regards

sonar-l10n-zh-25.1

---

communitybsl.properties

Hello there. communitybsl 1.15.2 is out.
SonarCloud project: https://sonarcloud.io/project/overview?id=1c-syntax_sonar-bsl-plugin-community
@ganncamp, Hi! 
Please, help me specify the versions correctly:
We need it so that version 1.15.1 is used BEFORE 25.1, and 1.15.2 on any, from 9.9 to the latest.
Thank you.

Add support SQ 25.1

---

update-center-source.properties

Validate locally by reproducing the error without the downloadUrl available when running a 10.7 Community Edition.
By adding the property in the file the modal gets displayed properly without JS errors:
https://github.com/user-attachments/assets/7466e0ae-9677-44a6-b550-0d6ec4f690c9

REL-3507 Add 2025.1 downloadUrl for <=10.7 compatibility

---

l10nzhtw.properties

Hello, I want to release a new version of sonar-l10n-zh-tw to support SonarQube 25.1 and 25.2. Thanks.
(Local screenshot)

Update sonar-l10n-zh-tw version to support SonarQube versions 25.1 and 25.2.

---

l10nzh.properties

Hi,
sonar-l10n-zh-plugin-25.6 has been released.
The main changes is support SonarQube 25.6.
The Download link and release notes: https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-25.6/sonar-l10n-zh-plugin-25.6.jar
And I added 25.2 to 25.5 for related version.
Thank you
Regards

sonar-l10n-zh-25.6

---

communitydelphi.properties

SonarDelphi v1.17.1 has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.17.1)
Thanks!

Release SonarDelphi plugin v.1.17.1

---

l10nzhtw.properties

SonarCloud:
https://sonarcloud.io/project/overview?id=JE-Chen_sonar-l10n-zh-tw
Screenshot:

Release sonar-l10n-zh-tw 1.3

---

communitydelphi.properties

SonarDelphi v1.18.0 has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.18.0)
Thanks!

Release SonarDelphi v1.18.0

---

l10nzh.properties

Hi,
sonar-l10n-zh-plugin-25.8 has been released.
The main changes is support SonarQube 25.8.
The Download link and release notes: https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-25.8/sonar-l10n-zh-plugin-25.8.jar
Thank you
Regards

sonar-l10n-zh-plugin 25.8
