findbugs.properties

https://community.sonarsource.com/t/new-release-sonar-findbugs-3-9-3/8059

release sonar-findbugs 3.9.3

---

apigee.properties

Announcement here :
https://community.sonarsource.com/t/new-release-sonar-apigee-plugin-2-0-0/8490

Declare sonar-apigee-plugin 2.0.0

---

quboo.properties

Plugin updated: 
* It now allows entering an API token for servers protected by authentication.
* A bug that prevented the score to be calculated has been fixed.
* Added truststore to properly verify the server certificate.

Quboo Plugin v1.0.5: Added support for authenticated servers and bugfix

---

groovy.properties

As discussed in https://github.com/pmayweg/sonar-groovy/issues/81#issuecomment-453172975, taking over the previous fork

Groovy 1.6

---

l10nzh.properties

sonar-l10n-zh-plugin-1.29 support SonarQube-7.9

sonar-l10n-zh-plugin-1.29 support SonarQube-7.9

---

crowd.properties

This contains a fix for the JAXB issue.

Crowd 2.1.3

---

mybatis.properties

Add sonar.mybatis.skip parameter to skip mybatis sensor

sonar-mybatis 1.0.2

---

mybatis.properties

sonar-mybatis 1.0.3
- fix several sonar issues
- skip dtd validation when using SaxParser, which shorten the analysis time

sonar-mybatis 1.0.3

---

mybatis.properties

- bugfix: fix NullPointerException on Windows
- add rule for check select *
link: https://community.sonarsource.com/t/new-release-mybatis-plugin-1-0-4/13823

add mybatis-1.0.4

---

mutationanalysis.properties

see [[NEW RELEASE] Mutation Analysis 1.5](https://community.sonarsource.com/t/new-release-mutation-analysis-1-5/13438)

[NEW RELEASE] Mutation analysis 1.5

---

mybatis.properties

- bugfix: handle TypeHandler,javaType,jdbcType,parameterMap,cache,cache-ref when generate reduced.xml
- update mybatis version to 3.5.2

sonar-mybatis 1.0.5

---

communitybsl.properties

Link to the thread https://community.sonarsource.com/t/new-release-1c-bsl-community-plugin-1-2-0/15392

communitybsl 1.2.0

---

quboo.properties

Updated Quboo Plugin to v1.0.6:
* Added two extra fields to export.
* Improved logs

Quboo v1.0.6

---

authoidc.properties

Updated OpenID Connect Authentication Plugin to v1.1.0:
* adds support for changing the login button's text, icon and background color
* provides a new login generation strategy (custom claim)
* adds support for additional scopes

OIDC Auth 1.1.0

---

mybatis.properties

- performance optimization
- remove useless hooks
- update sonar.apiVersion to 7.9

sonar-mybatis 1.0.6

---

communitybsl.properties

Link to the thread https://community.sonarsource.com/t/new-release-1c-bsl-community-plugin-1-3-1/16796

communitybsl 1.3.1

---

l10nzhtw.properties

The description and homepage url of l10nzhtw.properties are revised

Revise description and homepageurl

---

communitybsl.properties

Link to the thread: https://community.sonarsource.com/t/new-release-1c-bsl-community-plugin-1-4-0/19310

communitybsl 1.4.2

---

aemrules.properties

Release notes:
- HTL Support
- Dropped Slice Support

Release: AEMRules v1.0

---

.gitignore
scmtfvc.properties

*switch to Visual Studio 2019 using Microsoft.TeamFoundationServer.ExtendedClient
*fix user identification when connecting using Live ID
*check configuration for collection URI
*introduce build information

SCM-TFVC 2.3.0

---

authaad.properties

Update for the 1.2.0 release of the Auth AAD plugin.

Release Auth AAD 1.2.0

---

icode.properties

- i-Code analyzer is included directly in the plugin, there is no more need to install and launch i-Code
- analysis is now recursive
- support for java 11
- enhancement of the CI for the plugin

Add sonaricode 2.0.0

---

icode.properties

- Fix pluginKey and artifactId in icode.properties
- i-Code analyzer is included directly in the plugin, there is no more need to install and launch i-Code
- analysis is now recursive
- support for java 11
- enhancement of the CI for the plugin

New request to publish icode plugin 2.0.1

---

cnesreport.properties

* Support SonarQube 8 up to 8.2
* Support Java 11
* Compatibility with branch feature

Add Sonar CNES Report 3.2.2

---

findbugs.properties

We've released [sonar-findbugs version 4.0.0](https://github.com/spotbugs/sonar-findbugs/releases/tag/4.0.0), please add it to the marketplace.

Release sonar-findbugs 4.0.0

---

aemrules.properties

**AEMRules v1.1**
Release notes:
- Java Plugin 6.2 support

Release: AEMRules v1.1

---

quboo.properties

Changes:
* Upgraded API artifact to 7.4
* Added compatibility with Sonar > 8 by introducing `getDescription` method

Quboo v1.1.0. Added compatibility with Sonar 8.

---

communitybsl.properties

Link to the thread: https://community.sonarsource.com/t/new-release-1c-bsl-community-plugin-1-5-0/22705

community bsl 1.5.0

---

checkstyle.properties

https://community.sonarsource.com/t/new-release-sonar-checkstyle-4-31/23688

update checkstyle 4.31

---

cloudformation.properties

New version of the plugin released

Cloudformation 2.0.5 released

---

scannermsbuild.properties

https://discuss.sonarsource.com/t/sq-documentation-removed-link-to-net-fw-scanner-for-msbuild/4648

Fix Framework 4.6 properties

---

checkstyle.properties

https://community.sonarsource.com/t/new-release-sonar-checkstyle-4-32/24779

update checkstyle 4.32

---

communitybsl.properties

Link to the thread: https://community.sonarsource.com/t/new-release-1c-bsl-community-plugin-1-6-0/25957

communitybsl 1.6.0

---

checkstyle.properties

https://community.sonarsource.com/t/new-release-sonar-checkstyle-4-33/26371

checkstyle: update to 4.33

---

communitybsl.properties

Link to the thread https://community.sonarsource.com/t/new-release-1c-bsl-community-plugin-1-6-1/26697

communitybsl 1.6.1

---

l10nru.properties

Link to the thread: https://community.sonarsource.com/t/new-release-russian-pack-1-10/28330

Russian Pack 1.10

---

l10nru.properties

Link to the thread: https://community.sonarsource.com/t/new-release-russian-pack-8-0/28645

Russian pack 8.0

---

checkstyle.properties

https://community.sonarsource.com/t/new-release-sonar-checkstyle-4-34/29612

checkstyle: 4.34

---

codehawk.properties

updated properties for new release v1.4

new release v1.4

---

checkstyle.properties

https://community.sonarsource.com/t/new-release-sonar-checkstyle-8-35/29838

checkstyle: 8.35

---

devon4j.properties

[Thread in SonarSource forum](https://community.sonarsource.com/t/new-release-sonar-devon4j-plugin-2020-08-001/30224)

Added 2020.08.001 version of devon4j plugin

---

findbugs.properties

We've released [sonar-findbugs version 4.0.1](https://github.com/spotbugs/sonar-findbugs/releases/tag/4.0.1), please add it to the marketplace.
Here is [my post at forum for this change](https://community.sonarsource.com/t/new-release-sonar-findbugs-4-0-1/31461).

Release sonar-findbugs 4.0.1

---

communitybsl.properties

https://community.sonarsource.com/t/new-release-1c-bsl-community-plugin-1-7-0/31779

communitybsl 1.7.0

---

l10nzh.properties

sonar-l10n-zh-plugin-8.5

---

aemrules.properties

Bring back Java 8 runtime and build support by popular demand

AEM Rules Plugin v1.3 Release

---

scannerazure.properties

Please check the release note link

ScannerAzureDevOps 4.12 version

---

checkstyle.properties

https://community.sonarsource.com/t/new-release-sonar-checkstyle-8-37/34494

update checkstyle to 8.37

---

l10nzh.properties

sonar-l10n-zh-plugin-8.6

---

devon4j.properties

[Thread in SonarSource forum](https://community.sonarsource.com/t/new-release-sonar-devon4j-plugin-2020-12-002/36064)

Added 2020.12.002 of sonar-devon4j-plugin

---

checkstyle.properties

https://community.sonarsource.com/t/new-release-sonar-checkstyle-8-38/36199

checkstyle: 8.38

---

l10nru.properties

Release Russian pack 8.6 and fixes 8.0.2, 8.1.1, 8.2.1, 8.5.1

---

quboo.properties

Updated Quboo Gamification Plugin to 1.3.0

Quboo 1.3.0

---

checkstyle.properties

https://community.sonarsource.com/t/new-release-sonar-checkstyle-8-39/37660

checkstyle: 8.39

---

pmd.properties

This PR adds all properties to release Sonar-PMD 3.3.1 as announced in https://community.sonarsource.com/t/rff-sonar-pmd-plugin-3-3-1/37814/2
Thanks for checking and merging. :-)

Added properties for Sonar-PMD 3.3.1

---

checkstyle.properties

https://community.sonarsource.com/t/new-release-sonar-checkstyle-8-40/38806

update checkstyle to 8.40

---

findbugs.properties

To apply automation to the deployment process, format the properties file by this PR, then #186 can focus on the necessary content update for deploy.

Format the properties file for automation

---

l10nzh.properties

sonar-l10n-zh-plugin-8.8

---

l10nzh.properties

sonar-l10n-zh-plugin-8.9

---

apigee.properties

3.0.1 without sonar-xml dependency

3.0.1 without sonar-xml dependency

---

dependencycheck.properties

We've released sonar-dependency-check-plugin version 2.0.8 please add it to the marketplace.

Update dependency-check-sonar-plugin to 2.0.8

---

communitybsl.properties

Hello! New version of communitybsl is here.

1C (BSL) Community Plugin 1.9.0

---

groovy.properties

Announcement: https://community.sonarsource.com/t/new-release-sonar-groovy-plugin-1-7/44007

New Sonar-Groovy release 1.7

---

l10nzh.properties

sonar-l10n-zh-9.0

---

l10nru.properties

Support SonarQube 9.0 and small fixes

Support SonarQube 9.0 and small fixes

---

groovy.properties

Announcement: https://community.sonarsource.com/t/new-release-sonar-groovy-plugin-1-8/48333

New Sonar-Groovy release 1.8

---

quboo.properties

Updated Quboo plugin to version v1.4.1.

Quboo v1.4.1

---

communitybsl.properties

https://community.sonarsource.com/t/new-release-1c-bsl-community-plugin-1-10-0/49953

1C (BSL) Community plugin 1.10.0

---

cnesreport.properties

* SonarQube 8.9 LTS compatibility
* Add new metrics data in the reports (Quality Gate status, detailed technical debt, adherence to coding standard, etc.)
* Add graphs in report (evolution of the number of issues, evolution of technical debt ratio)
* Various bugfixes
And more details here : https://github.com/cnescatlab/sonar-cnes-report/releases/tag/4.0.0
*Compatibility only includes 8.9 LTS because we rely a lot on SQ APIs. 9.x versions may change them, and we don't have enough time to maintain the plugin for every intermediate SQ release before the next LTS.*

Add Sonar CNES Report version 4.0.0

---

checkstyle.properties

https://community.sonarsource.com/t/new-release-sonar-checkstyle-9-0-1/52405

upgrade checkstyle to 9.0.1

---

l10nzh.properties

sonar-l10n-zh-9.2

---

checkstyle.properties

https://community.sonarsource.com/t/new-release-sonar-checkstyle-9-1/54281

checkstyle: update to 9.1

---

cloudformation.properties

Cloudformation plugin 2.1.8

---

openedge.properties

... as I incorrectly understood the meaning of the sqVersions property.

Change minimum SonarQube version of opendge plugin

---

checkstyle.properties

https://community.sonarsource.com/t/new-release-sonar-checkstyle-9-2/54385

checkstyle: update to 9.2

---

checkstyle.properties

https://community.sonarsource.com/t/new-release-sonar-checkstyle-9-2-1/55863

checkstyle: update to 9.2.1

---

authoidc.properties

Updated OpenID Connect Authentication Plugin to v2.1.1:
* fixes some issues with the newly added auto-login servlet filter

OIDC Auth 2.1.1

---

l10nzh.properties

sonar-l10n-zh-9.3

---

checkstyle.properties

https://community.sonarsource.com/t/new-release-sonar-checkstyle-9-3/57412

checkstyle: update to 9.3

---

mutationanalysis.properties

Maintenance Release to Support Sonarqube 9.1 and Pitest 1.7.1

Mutation Analysis 1.6

---

l10nzh.properties

[l10n-zh] support 9.4 and remove versions lower than 8.9

---

checkstyle.properties

https://community.sonarsource.com/t/new-release-sonar-checkstyle-10-1/60999

checkstyle: update to 10.1

---

aemrules.properties

New release of AEM Rules after the conversation  in https://community.sonarsource.com/t/new-release-aem-rules-1-5/61314

AEM Rules release 1.6

---

communitybsl.properties

New version https://community.sonarsource.com/t/new-release-1c-bsl-community-plugin-1-11-0/63868

1c bsl community plugin. New version 1.11.0

---

citymodel.properties

Site currently gives a 503 on the download URL, failing the generation job. After waiting several hours for this to clear, I'm commenting out the public version so I can run the job.

comment out public version; gen job failing

---

scannermsbuild.properties

Added Core31 version in prep for dropping 2.1

Updated for Scanner for .NET 5.6.0.48455

---

l10nzh.properties

sonar-l10n-zh-9.5

---

authaad.properties

Update for the 1.3.1 AAD authentication plugin.

Release AuthAAD 1.3.1

---

update-center-source.properties

Updated for release 9.6

---

checkstyle.properties

https://community.sonarsource.com/t/new-release-sonar-checkstyle-10-3-2/69754

checkstyle: update to 10.3.2

---

l10nzh.properties

l10n-zh 9.6

---

update-center-source.properties

Removed faster analysis for Kotlin from short description for SonarQube 9.6.

REL-2362 Removed faster analysis for Kotlin

---

update-center-source.properties

Bug fix release 9.7.1 is added.

9.7.1 Release updated

---

scannerazure.properties

I added 5.9.0 and 5.10.0 in the same batch

Update Scanner for Azure DevOps to 5.10.0

---

l10nru.properties

sonar-l10n-ru-plugin. version 9.9

---

checkstyle.properties

checkstyle: update to 10.7.0

---

checkstyle.properties

checkstyle: update to 10.8.1

---

scannerant.properties
scannerazure.properties
scannercli.properties
scannergradle.properties
scannerjenkins.properties
scannermaven.properties

Updated:
- Sonar Scanner CLI
- Sonar Scanner Maven
- Sonar Scanner Gradle
- Sonar Scanner Ant
- Sonar Scanner Jenkins
- Sonar Scanner VSTS/ADO

Update Sonar scanners with proper Jira links for release notes

---

checkstyle.properties

checkstyle: update to 10.9.3

---

checkstyle.properties

checkstyle: update to 10.11.0

---

checkstyle.properties

checkstyle: update to 10.12.0

---

communitybsl.properties

Updated SonarQube libraries to version 9.9+ & speed optimization
SonarQube page https://sonarcloud.io/summary/new_code?id=1c-syntax_sonar-bsl-plugin-community

1c bsl community plugin. New version 1.13.0 

---

scannergradle.properties

I decided to replace the previous one, as it is a bugfix

Add scanner for Gradle 4.3.1.3277

---

softvis3d.properties

* Add 1.3.0 release of de.rinderle.softvis3d plugin.

sonar-softvis3d-plugin 1.3.0

---

l10nru.properties

sonar-l10n-ru-plugin. version 10.0

---

l10nru.properties

sonar-l10n-ru-plugin. version 10.1

---

checkstyle.properties

checkstyle: update to 10.12.5

---

.cirrus-private.yml
.cirrus-public.yml
.cirrus.star
.cirrus/Dockerfile
.gitignore
po-generate-update-center-prod/.envrc
po-generate-update-center-prod/README.md
po-generate-update-center-prod/generate.sh
po-generate-update-center-prod/prepare_transfer_dir.sh
po-generate-update-center-prod/upload.sh

BUILD-4142 depends on https://github.com/SonarSource/re-terraform-aws-vault/pull/846

BUILD-4142 po-generate-update-center-prod

---

ibmixaemrules.properties

Version 1.3 release of the ibmix-aem-sonar-rules plugin
SonarCloud dashboard - https://sonarcloud.io/summary/new_code?id=ibmix-aem-sonar-rules

Release ibmix-aem-sonar-rules plugin v1.3

---

l10nru.properties

Add support SQ 10.3 and fixes for 10.2

sonar-l10n-ru-plugin. version 10.3 + fixes for 10.2

---

yaml.properties

YAML: new versions 1.8.1, 1.9.0 and 1.9.1

---

communitydelphi.properties

SonarDelphi v.1.1.0 has been released:
* [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.1.0)
* [SonarCloud](https://sonarcloud.io/project/overview?id=integrated-application-development_sonar-delphi)
Thanks!

Release SonarDelphi plugin v1.1.0

---

openedge.properties

Version 2.24.2 has been released two weeks ago, could you please update the marketplace ?
SonarCloud project: https://sonarcloud.io/summary/new_code?id=eu.rssw%3Asonar-openedge
Thank you !

OpenEdge plugin: upgrade to 2.24.2

---

openedge.properties

Fixes job failure; jar is no longer downloadable.

archive current version

---

communitydelphi.properties

v1.2.0 of the SonarDelphi plugin has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.2.0)

Release SonarDelphi plugin v1.2.0

---

communitydelphi.properties

SonarDelphi v.1.3.0 has been released:
* [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.3.0)
* [SonarCloud](https://sonarcloud.io/project/overview?id=integrated-application-development_sonar-delphi)
Thanks!

Release SonarDelphi plugin v1.3.0

---

.cirrus-private.yml
po-generate-update-center-prod/README.md
po-generate-update-center-prod/upload-sc.sh
po-generate-update-center-prod/upload.sh

Upload scannerazuresc.json to https://downloads.sonarsource.com/?prefix=sonarqube/update

BUILD-4227 scannerazuresc.json upload

---

checkstyle.properties

checkstyle: update to 10.14.1

---

scannerjenkins.properties

https://sonarsource.atlassian.net/browse/REL-2996

Scanner for Jenkins 2.17.2

---

communitydelphi.properties

v1.4.0 of the SonarDelphi plugin has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.4.0)

Release SonarDelphi plugin v1.4.0

---

po-generate-update-center-prod/generate.sh

[Release note](https://github.com/SonarSource/sonar-update-center/releases/tag/1.32.0.2441)

Upgrade update-center version to 1.32.0.2441

---

checkstyle.properties

checkstyle: update to 10.15.0

---

communityrust.properties

1. I am the new maintainer of sonar-rust plugin. I updated the information about plugin with valid links for old releases and new version - 0.2.3

Update communityrust.properties for sonar-rust plugin

---

communitydelphi.properties

SonarDelphi v.1.5.0 has been released:
* [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.5.0)
* [SonarCloud](https://sonarcloud.io/project/overview?id=integrated-application-development_sonar-delphi)
Thanks!

Release SonarDelphi plugin v1.5.0

---

checkstyle.properties

checkstyle: update to 10.16.0

---

checkstyle.properties

checkstyle: update to 10.17.0

---

communitydelphi.properties

v1.6.0 of the SonarDelphi plugin has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.6.0)

Release SonarDelphi plugin v1.6.0

---

l10nru.properties

Add support sq 10.4

---

update-center-source-sc.properties

Declare a fake ltsVersion and ltaVersion

Declare a fake ltsVersion and ltaVersion

---

communitydelphi.properties

SonarDelphi v.1.7.0 has been released:
* [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.7.0)
* [SonarCloud](https://sonarcloud.io/project/overview?id=integrated-application-development_sonar-delphi)
Thanks!

Release SonarDelphi plugin v1.7.0

---

l10nru.properties

Hello!
Here is a new release of sonar-l10-ru with new translations for SonarQube 10.5.

sonar-l10-ru v10.5

---

communitybsl.properties

Changes
* BSL Language Server updated to version v0.23.1 (performance optimization, fixes)
* New setting: filtering by subsystems 
SonarQube page https://sonarcloud.io/summary/new_code?id=1c-syntax_sonar-bsl-plugin-community

1c bsl community plugin. New version 1.15.0

---

l10nru.properties

Support SonarQube 10.6

---

communitydelphi.properties

v1.8.0 of the SonarDelphi plugin has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.8.0)

Release SonarDelphi plugin v1.8.0

---

communitydelphi.properties

SonarDelphi v1.9.0 has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.9.0)
Thanks!

Release SonarDelphi plugin v1.9.0

---

scannercli.properties

Support PKCS12 truststore generated with OpenSSL

Scanner CLI 6.2.0.4584

---

communitydelphi.properties

v1.10.0 of the SonarDelphi plugin has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.10.0)
Please add it to the marketplace. Thanks!

Release SonarDelphi plugin v1.10.0

---

scannercli.properties

[REL-3312](https://sonarsource.atlassian.net/browse/REL-3312)
[REL-3312]: https://sonarsource.atlassian.net/browse/REL-3312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update ScannerCLI to 6.2.1.4610

---

checkstyle.properties

checkstyle: update to 10.19.0

---

l10nzhtw.properties

Update l10nzhtw.properties #603

---

communitydelphi.properties

v1.11.0 of the SonarDelphi plugin has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.11.0)
Please add it to the marketplace - thanks!

Release SonarDelphi plugin v1.11.0

---

ecocodecsharp.properties

Hi,
ecoCode C# plugin 1.5.1 has been released.
Changes from last SonarQube marketplace integration (1.1.0), please check following changelogs :
from 1.1.0 to 1.5.1 : https://github.com/green-code-initiative/ecoCode-csharp-sonarqube/releases/tag/1.5.1
The corresponding SonarCloud project: https://sonarcloud.io/project/overview?id=green-code-initiative_ecoCode-csharp-sonarqube
Thank you
Regards

Release C# ecoCode Plugin v1.5.1

---

.cirrus-public.yml
po-generate-update-center-prod/generate.sh

I couldn't find any trace of these parameters that are passed to the code. I validated locally and the jobs work just fine without them. If you have some secret knowledge about them feel free to share and reject the PR.

NO-JIRA removed the parameters to mvn goal that were not used anymore

---

checkstyle.properties

checkstyle: update to 10.20.1

---

ibmixaemrules.properties

Version 1.4.1 release of the ibmix-aem-sonar-rules plugin
SonarCloud dashboard - https://sonarcloud.io/summary/new_code?id=ibmix-aem-sonar-rules

Release ibmix-aem-sonar-rules plugin v1.4.1

---

.cirrus-private.yml

Depends on https://github.com/SonarSource/re-terraform-aws-vault/pull/3372

BUILD-6538 use public reader

---

update-center-source.properties

It can't be merged as download links are not yet updated on the website

REL-3426 Release SonarQube 9.9.8

---

checkstyle.properties

i saw that the compatibility changed in the properties files. please let me know if i applied the correct change, or what i would need to adapt now. 😉

checkstyle: update to 10.20.2

---

communitydelphi.properties

v1.12.2 of the SonarDelphi plugin has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.12.2)
Please add it to the marketplace - thanks!

Release SonarDelphi plugin v1.12.2

---

l10nru.properties

Add support SQ 10.8/24.12  and smal fixes

Support SQ 10.8/24.12

---

l10nru.properties

Add support SQ 25.1

---

communitydelphi.properties

SonarDelphi v1.13.0 has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.13.0)
Thanks!

Release SonarDelphi plugin v1.13.0

---

communitydelphi.properties

v1.14.0 of the SonarDelphi plugin has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.14.0)
Please add it to the marketplace - thanks!

Release SonarDelphi plugin v1.14.0

---

communitydelphi.properties

v1.14.1 of the SonarDelphi plugin has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.14.1)
Please add it to the marketplace - thanks!

Release SonarDelphi plugin v1.14.1

---

communitybsl.properties

Hello! :smiley:
CommunityBSL 1.16.1 is out.
SonarCloud project: https://sonarcloud.io/project/overview?id=1c-syntax_sonar-bsl-plugin-community

CommunityBSL 1.16.1

---

l10nzhtw.properties

Comment out unavailable sonar-l10n-zh-tw-plugin-1.1

---

communitydelphi.properties

SonarDelphi v1.15.0 has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.15.0)
Thanks!

Release SonarDelphi plugin v1.15.0

---

checkstyle.properties

checkstyle: update to 10.23.0

---

scannermsbuild.properties

REL-3689 SonarScanner for .NET 10.1.2

---

creedengojavascript.properties

Hello 👋 
We have released a new version of creedengo-javascript plugin!
🔗 [Official 2.1.0 release announcement](https://github.com/green-code-initiative/creedengo-javascript/releases/tag/2.1.0)
🏗️ [SonarCloud project page](https://sonarcloud.io/project/overview?id=green-code-initiative_ecoCode-linter)
Thank you,
Regards

Upgrade JS Creedengo plugin to 2.1.0

---

communitydelphi.properties

v1.16.0 of the SonarDelphi plugin has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.16.0)

Release SonarDelphi plugin v1.16.0

---

communitydelphi.properties

v1.17.0 of the SonarDelphi plugin has been released:
- [Release Notes](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.17.0)

Release SonarDelphi plugin v1.17.0

---

scannernpm.properties
update-center-source.properties

Following example from Python Scanner - https://github.com/SonarSource/sonar-update-center-properties/pull/734

SCANNPM-88 Add entry to sonar-update-center

---

l10nru.properties

Add support SQ 25.7
